### ISSUE TITLE
Malformed OpenAPI Specs

### ISSUE THREAD

**Issue by tkcranny** [webflow/openapi-spec#1]
The V2 and V2-beta specifications currently aren't passing OpenAPI validation. 

These errors cause problems with [editor-next.swagger.io](https://editor-next.swagger.io/) and generating clients with [openapi-ts/openapi-typescript](https://github.com/openapi-ts/openapi-typescript).

The issues seem to arise because of:
- `properties: null` ([e.g.](https://github.com/webflow/openapi-spec/blob/64c0ce98f1b695610dc692aaf561dddb474d8ce6/openapi/v2.yml#L24449))
- `readonly: null` fields ([e.g.](https://github.com/webflow/openapi-spec/blob/64c0ce98f1b695610dc692aaf561dddb474d8ce6/openapi/v2.yml#L642))
- `description: null` ([e.g.](https://github.com/webflow/openapi-spec/blob/64c0ce98f1b695610dc692aaf561dddb474d8ce6/openapi/v2.yml#L21943))
- Duplicate enum entries ([e.g.](https://github.com/webflow/openapi-spec/blob/64c0ce98f1b695610dc692aaf561dddb474d8ce6/openapi/v2.yml#L11454-L11484) `standard-table`, `standard-exempt` appear twice here)
- Some other malformed `properties` sections that don't conform to JSON Schema patterns ([e.g.](https://github.com/webflow/openapi-spec/blob/64c0ce98f1b695610dc692aaf561dddb474d8ce6/openapi/v2.yml#L1221-L1288))
- OpenAPI prefers `examples` instead of singular `example` fields.

There's also no `schemas` section to simplify the data types for API clients.

**Comment by victoriaplummer** [comment]
Hi @tkcranny  ,

Thank you for bringing these issues to our attention. We've addressed and fixed the following points:

- Fixed properties: `null` where it occurred
- Fixed readonly: `null` fields where they occurred
- Fixed description: `null` and replaced with descriptions where applicable
- Eliminated duplicate enum entries
- Corrected malformed properties sections to conform to JSON Schema patterns

**Regarding the remaining issues:**

- **OpenAPI prefers examples instead of singular example fields:** As we move forward, we'll look to standardize this across our specifications to align with OpenAPI best practices.

- **No schemas section to simplify the data types for API clients:** Currently, we bundle our API from many different files. We will look into incorporating a schemas section into our spec to improve consistency and ease of use for API clients.

We appreciate your feedback and patience as we continue to improve our specifications. If you encounter any further issues or have additional suggestions, please don't hesitate to let us know.

Best regards,
Vic

**Comment by tkcranny** [comment]
Thanks @victoriaplummer.

Is there any timeline on when these fixes will actually by published?
